swagger: '2.0'
info:
  version: 1.0.0
  title: LocationIQ
  description: 'LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.'
host: eu1.locationiq.com
basePath: /v1
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  key:
    name: key
    type: apiKey
    in: query
paths:
  /search.php:
    get:
      operationId: search
      summary: Forward Geocoding
      description: The Search API allows converting addresses, such as a street address, into geographic coordinates (latitude and longitude). These coordinates can serve various use-cases, from placing markers on a map to helping algorithms determine nearby bus stops. This process is also known as Forward Geocoding.
      tags:
        - Search
      parameters:
        - name: q
          in: query
          description: Address to geocode
          required: true
          type: string
        - name: format
          in: query
          description: Format to geocode. Only JSON supported for SDKs
          required: true
          type: string
          enum:
            - json
        - name: normalizecity
          in: query
          description: 'For responses with no city value in the address section, the next available element in this order - city_district, locality, town, borough, municipality, village, hamlet, quarter, neighbourhood - from the address section will be normalized to city. Defaults to 1 for SDKs.'
          required: true
          type: integer
          enum:
            - 1
        - name: addressdetails
          in: query
          description: Include a breakdown of the address into elements. Defaults to 0.
          required: false
          type: integer
          enum:
            - 0
            - 1
        - name: viewbox
          in: query
          description: 'The preferred area to find search results.  To restrict results to those within the viewbox, use along with the bounded option.'
          required: false
          type: string
        - name: bounded
          in: query
          description: Restrict the results to only items contained with the viewbox
          required: false
          type: integer
          enum:
            - 0
            - 1
        - name: limit
          in: query
          description: Limit the number of returned results. Default is 10.
          required: false
          type: integer
          default: 10
        - name: accept-language
          in: query
          description: 'Preferred language order for showing search results, overrides the value specified in the Accept-Language HTTP header. Defaults to en. To use native language for the response when available, use accept-language=native'
          required: false
          type: string
        - name: countrycodes
          in: query
          description: Limit search to a list of countries.
          required: false
          type: string
        - name: namedetails
          in: query
          description: 'Include a list of alternative names in the results. These may include language variants, references, operator and brand.'
          required: false
          type: integer
          enum:
            - 0
            - 1
        - name: dedupe
          in: query
          description: 'Sometimes you have several objects in OSM identifying the same place or object in reality. The simplest case is a street being split in many different OSM ways due to different characteristics. Nominatim will attempt to detect such duplicates and only return one match; this is controlled by the dedupe parameter which defaults to 1. Since the limit is, for reasons of efficiency, enforced before and not after de-duplicating, it is possible that de-duplicating leaves you with less results than requested.'
          required: false
          type: integer
          enum:
            - 0
            - 1
        - name: extratags
          in: query
          description: 'Include additional information in the result if available, e.g. wikipedia link, opening hours.'
          required: false
          type: integer
          enum:
            - 0
            - 1
      responses:
        '200':
          description: OK
          schema:
            title: fowardresponse
            type: array
            items:
              $ref: '#/definitions/location'
          examples:
            application/json:
              - place_id: '83874904'
                licence: '© LocationIQ.com CC BY 4.0, Data © OpenStreetMap contributors, ODbL 1.0'
                osm_type: way
                osm_id: '34633854'
                boundingbox:
                  - '40.7479226'
                  - '40.7489422'
                  - '-73.9864855'
                  - '-73.9848259'
                lat: '40.7484284'
                lon: '-73.9856546198733'
                display_name: 'Empire State Building, 350, 5th Avenue, Korea Town, Midtown South, Manhattan, Manhattan Community Board 5, New York County, New York City, New York, 10001, United States of America'
                class: tourism
                type: attraction
                importance: 0.43072416348613
                icon: 'https://locationiq.org/static/images/mapicons/poi_point_of_interest.p.20.png'
                address:
                  name: Empire State Building
                  house_number: '350'
                  road: 5th Avenue
                  commercial: Korea Town
                  suburb: Midtown South
                  city_district: Manhattan
                  city: New York City
                  county: New York County
                  state: New York
                  postcode: '10001'
                  country: United States of America
                  country_code: us
              - place_id: '28210682'
                licence: '© LocationIQ.com CC BY 4.0, Data © OpenStreetMap contributors, ODbL 1.0'
                osm_type: node
                osm_id: '2709306673'
                boundingbox:
                  - '40.7481128'
                  - '40.7482128'
                  - '-73.9850458'
                  - '-73.9849458'
                lat: '40.7481628'
                lon: '-73.9849958'
                display_name: 'Empire State Building, 350, 5th Avenue, Korea Town, Midtown South, Manhattan, Manhattan Community Board 5, New York County, New York City, New York, 10001, United States of America'
                class: tourism
                type: attraction
                importance: 0.30025
                icon: 'https://locationiq.org/static/images/mapicons/poi_point_of_interest.p.20.png'
                address:
                  name: Empire State Building
                  house_number: '350'
                  road: 5th Avenue
                  commercial: Korea Town
                  suburb: Midtown South
                  city_district: Manhattan
                  city: New York City
                  county: New York County
                  state: New York
                  postcode: '10001'
                  country: United States of America
                  country_code: us
              - place_id: '66500562'
                licence: '© LocationIQ.com CC BY 4.0, Data © OpenStreetMap contributors, ODbL 1.0'
                osm_type: node
                osm_id: '5552887205'
                boundingbox:
                  - '52.2956835'
                  - '52.2957835'
                  - '16.7553074'
                  - '16.7554074'
                lat: '52.2957335'
                lon: '16.7553574'
                display_name: 'Empire State Building, Poznańska, Trzebaw, gmina Stęszew, powiat poznański, Greater Poland Voivodeship, Poland'
                class: tourism
                type: artwork
                importance: 0.30025
                icon: 'https://locationiq.org/static/images/mapicons/tourist_art_gallery2.p.20.png'
                address:
                  name: Empire State Building
                  road: Poznańska
                  village: Trzebaw
                  county: gmina Stęszew
                  state: Greater Poland Voivodeship
                  country: Poland
                  country_code: pl
                  city: Trzebaw
        '400':
          description: 'Required parameters are missing, or invalid'
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Invalid Request
        '401':
          description: An invalid API key was provided / Key not active
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Invalid key
        '404':
          description: No location or places were found for the given input
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Unable to geocode
        '429':
          description: Request exceeded the rate-limits set on your account
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Rate Limited Second
        '500':
          description: 'This is an error on the server''s side, we monitor this 24x7 and you should try again.'
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Unknown error - Please try again after some time
      security:
        - key: []
  /reverse.php:
    get:
      operationId: reverse
      summary: Reverse Geocoding
      description: Reverse geocoding is the process of converting a coordinate or location (latitude, longitude) to a readable address or place name. This permits the identification of nearby street addresses, places, and/or area subdivisions such as a neighborhood, county, state, or country.
      tags:
        - reverse
      parameters:
        - name: lat
          in: query
          description: Latitude of the location to generate an address for.
          required: true
          type: number
          minimum: -90
          maximum: 90
        - name: lon
          in: query
          description: Longitude of the location to generate an address for.
          required: true
          type: number
          minimum: -180
          maximum: 180
        - name: format
          in: query
          description: Format to geocode. Only JSON supported for SDKs
          required: true
          type: string
          enum:
            - json
        - name: normalizecity
          in: query
          description: Normalizes village to city level data to city
          required: true
          type: integer
          enum:
            - 1
        - name: addressdetails
          in: query
          description: Include a breakdown of the address into elements. Defaults to 1.
          required: false
          type: integer
          enum:
            - 0
            - 1
          default: 1
        - name: accept-language
          in: query
          description: 'Preferred language order for showing search results, overrides the value specified in the Accept-Language HTTP header. Defaults to en. To use native language for the response when available, use accept-language=native'
          required: false
          type: string
        - name: namedetails
          in: query
          description: 'Include a list of alternative names in the results. These may include language variants, references, operator and brand.'
          required: false
          type: integer
          enum:
            - 0
            - 1
        - name: extratags
          in: query
          description: 'Include additional information in the result if available, e.g. wikipedia link, opening hours.'
          required: false
          type: integer
          enum:
            - 0
            - 1
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/location'
          examples:
            application/json:
              place_id: '83874904'
              licence: '© LocationIQ.com CC BY 4.0, Data © OpenStreetMap contributors, ODbL 1.0'
              osm_type: way
              osm_id: '34633854'
              lat: '40.7484284'
              lon: '-73.9856546198733'
              display_name: 'Empire State Building, 350, 5th Avenue, Korea Town, Midtown South, Manhattan, Manhattan Community Board 5, New York County, New York City, New York, 10001, United States of America'
              address:
                name: Empire State Building
                house_number: '350'
                road: 5th Avenue
                commercial: Korea Town
                suburb: Midtown South
                city_district: Manhattan
                city: New York City
                county: New York County
                state: New York
                postcode: '10001'
                country: United States of America
                country_code: us
              boundingbox:
                - '40.7479226'
                - '40.7489422'
                - '-73.9864855'
                - '-73.9848259'
        '400':
          description: 'Required parameters are missing, or invalid'
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Invalid Request
        '401':
          description: An invalid API key was provided / Key not active
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Key not active - Please write to hello@locationiq.org
        '404':
          description: No location or places were found for the given input
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Unable to geocode
        '429':
          description: ''
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Rate Limited Second
        '500':
          description: Unknown error - Please try again after some time
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Unknown error - Please try again after some time
      security:
        - key: []
  /balance.php:
    get:
      operationId: balance
      tags:
        - Balance
      description: The Balance API provides a count of request credits left in the user's account for the day. Balance is reset at midnight UTC everyday (00:00 UTC).
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/balance'
          examples:
            application/json:
              status: ok
              balance:
                day: 30000
        '400':
          description: ''
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Invalid Request
        '401':
          description: ''
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Invalid key
        '429':
          description: ''
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Rate Limited Day
        '500':
          description: ''
          schema:
            $ref: '#/definitions/error'
          examples:
            application/json:
              error: Unknown error - Please try again after some time
      security:
        - key: []
definitions:
  address:
    title: address
    type: object
    properties:
      house_number:
        type: string
      road:
        type: string
      residential:
        type: string
      village:
        type: string
      county:
        type: string
      state:
        type: string
      postcode:
        type: string
      country:
        type: string
      country_code:
        type: string
      city:
        type: string
    example:
      house_number: '3894'
      road: Spring Mill Way
      residential: Hunter’s Point
      village: Landen
      county: Warren County
      state: Ohio
      postcode: '45039'
      country: United States of America
      country_code: us
      city: Landen
  balance:
    title: balance
    type: object
    properties:
      status:
        type: string
      balance:
          $ref: '#/definitions/daybalance'
    example:
      status: ok
      balance:
        day: 547933
  daybalance:
    title: daybalance
    type: object
    properties:
      day:
        type: integer
  error:
    title: error
    type: object
    properties:
      error:
        type: string
    example:
      error: Invalid key
  location:
    title: location
    type: object
    properties:
      place_id:
        type: string
      licence:
        type: string
      osm_type:
        type: string
      osm_id:
        type: string
      boundingbox:
        type: array
        items:
          type: string
      lat:
        type: string
      lon:
        type: string
      display_name:
        type: string
      class:
        type: string
      type:
        type: string
      importance:
        type: number
      address:
        $ref: '#/definitions/address'
    example:
      place_id: '223483692'
      licence: '© LocationIQ.com CC BY 4.0, Data © OpenStreetMap contributors, ODbL 1.0'
      osm_type: way
      osm_id: '19301621'
      boundingbox:
        - '39.307405567782'
        - '39.307505567782'
        - '-84.292824851595'
        - '-84.292724851595'
      lat: '39.3074555677816'
      lon: '-84.2927748515948'
      display_name: '3894, Spring Mill Way, Hunter’s Point, Landen, Warren County, Ohio, 45039, United States of America'
      class: place
      type: house
      importance: 0.62025
      address:
        house_number: '3894'
        road: Spring Mill Way
        residential: Hunter’s Point
        village: Landen
        county: Warren County
        state: Ohio
        postcode: '45039'
        country: United States of America
        country_code: us
        city: Landen
